services:
  peer0.garamm.dev:
    image: hyperledger/fabric-peer:latest
    container_name: peer0.garamm.dev
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.garamm.dev
      - CORE_PEER_ADDRESS=peer0.garamm.dev:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.garamm.dev:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.garamm.dev:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.garamm.dev:7051
      - CORE_PEER_LOCALMSPID=GarammMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.garamm.dev:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0garammdev"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-workspace
    volumes:
      - ./organizations/peerOrganizations/garamm.dev/peers/peer0.garamm.dev:/etc/hyperledger/fabric
      - peer0.garamm.dev:/var/hyperledger/production
      - ./peercfg:/etc/hyperledger/peercfg
      - /run/user/1000/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - fabric-workspace

networks:
  fabric-workspace:
    name: fabric-workspace

volumes:
  peer0.garamm.dev:
    driver: local