Organizations:
  - &Garamm
    Name: GarammMSP
    ID: GarammMSP
    MSPDir: organizations/peerOrganizations/garamm.dev/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('GarammMSP.admin', 'GarammMSP.peer', 'GarammMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('GarammMSP.admin', 'GarammMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('GarammMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('GarammMSP.peer')"